#!/stage1/busybox sh
echo "OHAI, stage1 init starting" > /dev/kmsg
export _PATH="$PATH"
export PATH=/stage1

force_recovery="0"

busybox cd /
busybox date >>boot.txt
exec >>boot.txt 2>&1
busybox rm init
busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys

while ! busybox test -d /sys/devices/platform/s3c-sdhci.0/mmc_host/mmc0/mmc0:0001 ; do 
	echo "Waiting for internal mmc..."
busybox sleep 1 
done

busybox mount -t ext4 /dev/block/mmcblk0p1 /cache
busybox mount -t ext4 /dev/block/mmcblk0p2 /system

image=/stage1/ramdisk.cpio

if  busybox grep -q "recovery" /proc/cmdline || busybox grep -q "init=/init bootmode=0 loglevel=0 androidboot.serialno=0000045600000123 bootmode=2" /proc/cmdline || busybox grep -q "init=/init bootmode=0 loglevel=4 androidboot.serialno=0000045600000123 bootmode=2" /proc/cmdline || busybox grep -q "bootmode=2" /proc/cmdline || busybox test -e /cache/.startrecovery || busybox grep -q bootmode=2 /proc/cmdline  ; then
	# recovery boot
	busybox rm -fr /cache/.startrecovery
	image=/stage1/ramdisk-recovery.cpio

	# disable lpm
	busybox echo 0 > /sys/class/power_supply/battery/charging_mode_booting
elif ! busybox test -e /system/build.prop; then
	# emergency boot
	busybox umount /cache
	make_ext4fs /dev/block/mmcblk0p1
	busybox mount -t ext4 /dev/block/mmcblk0p1 /cache
	busybox mkdir /cache/recovery

	image=/stage1/ramdisk-recovery.cpio

	# disable lpm
	busybox echo 0 > /sys/class/power_supply/battery/charging_mode_booting
	# Bigmem
	# elif ! busybox grep -q bootmode=10 /proc/cmdline ; then

fi

busybox umount /cache
busybox umount /system

busybox cpio -i < $image

busybox umount /sys
busybox umount /proc
busybox date >>boot.txt
echo "stage1 log:" > /dev/kmsg
busybox cat boot.txt > /dev/kmsg
busybox rm -fr /stage1 /dev/*
export PATH="${_PATH}"
exec /init